name: AppImage

on:
  push:
    branches: [ master, appimage ]
  pull_request:
    branches: [ master ]

jobs:
  build-appimage:
    runs-on: ubuntu-18.04

    steps:
      - name: install dependencies
        run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt install -y build-essential python3-pip libxml2-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev gcc-10 g++-10
          sudo pip3 install --upgrade pip cmake
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
      - name: "Clone w/ submodules"
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Make AppImage
        run: sh ./scripts/appimage.sh
      - uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: './*.AppImage*'
