name: Release

on:
  push:
    branches: [ master ]
    tags:
      - v*

name: CI

jobs:
  build_appimage:
    name: "Build on Ubuntu"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - { 
            name: "Ubuntu",
            os:   "ubuntu-20.04",
            cc:   "gcc-10",
            cxx:  "g++-10"
          }
      fail-fast: false
    env:
        CC:         ${{ matrix.config.cc }}
        CXX:        ${{ matrix.config.cxx }}
        app_dir:    /tmp/tmp.JbLDI6xwc5
        bld_dir:    build_dir
    steps:
      - name: "Clone w/ submodules"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"
      - name: Update apt
        run: sudo apt update
      - name: Install missing packages
        run: sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
      - name: Check config
        run: |
          $CC --version
          $CXX --version
      - name: Configure
        run: cmake -S . -B $bld_dir -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC --install-prefix $app_dir/usr -DARB_ARCH=x86-64-v2 -DBUILD_SHARED_LIBS=OFF
      - name: Build
        run: cmake --build $bld_dir -j 2
      - name: Install
        run: cmake --install $bld_dir
      - name: Get Linuxdeploy
        run: wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
      - name: Mark executable
        run: chmod +x ./linuxdeploy-x86_64.AppImage
      - name: Package Arbor GUI AppImage
        run: ./linuxdeploy-x86_64.AppImage --appdir="$app_dir" --output=appimage
      - name: Delete Linuxdeploy
        run: rm -f ./linuxdeploy-x86_64.AppImage
      - uses: actions/upload-artifact@v3
        with:
          name: linux appimage
          path: './*.AppImage*'
  build_diskim:
    name: "Build on MacOS"
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "MacOS",
            os:   "macos-11",
            cc:   "clang",
            cxx:  "clang++"
          }
    env:
        CC:         ${{ matrix.config.cc }}
        CXX:        ${{ matrix.config.cxx }}
    steps:
      - name: "Clone w/ submodules"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: "recursive"
      - name: Check config
        run: |
          $CC --version
          $CXX --version
      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DARBORGUI_BUILD_BUNDLE=ON -DBUILD_SHARED_LIBS=OFF
      - name: Build
        run: cmake --build build -j 2 --target package
      - name: Upload .dmg
        uses: actions/upload-artifact@v3
        with:
          name: apple dmg
          path: build/*.dmg

  make_rel:
    name: Make Release
    needs: [build_diskim, build_appimage]
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: "Get artifacts"
        uses: actions/download-artifact@v2
      - name: Move and rename appimage
        run: mv */*.AppImage arbor-gui.AppImage
      - name: Move and rename dmg
        run: mv */*.dmg arbor-gui.dmg
      - name: "Make Release"
        uses: ncipollo/release-action@v1
        with:
          omitBody: true
          draft: true
          prerelease: false
          artifacts: '*.dmg,*.AppImage'
          token: ${{ secrets.GITHUB_TOKEN }}
          